# Generated by Django 5.1.1 on 2024-09-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_customer_first_name_alter_customer_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "The order is placed"),
                    ("PROCESSING", "The order is being prepared"),
                    ("SHIPPED", "The order is on the way to the customer"),
                    ("DELIVERED", "The order has been delivered"),
                    ("RETURNED", "The order was returned"),
                    ("CANCELED", "The order was canceled"),
                ],
                default="PENDING",
                max_length=23,
            ),
        ),
    ]
