# Generated by Django 5.1.1 on 2024-09-20 16:14

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(
                max_length=50, validators=[store.validators.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(
                max_length=50, validators=[store.validators.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[store.validators.validate_username],
            ),
        ),
    ]
