# Generated by Django 5.1.1 on 2024-09-24 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_cartitem_quantity_alter_orderitem_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Address can only contain letters, numbers, spaces, and the following symbols: , . -",
                        regex="^[\\w\\s,.-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+380XXXXXXXXX'.",
                        regex="^\\+380\\d{9}$",
                    )
                ],
            ),
        ),
    ]
